/*
 * Este Software tem Objetivo Educacional
 * Para fins de aprendizagem e avaliacao na
 * Na Disciplina de Programa��o Orientada a Objetos - Avan�ada
 *  do Curso de Analise de Sistemas da Fatec - Ipiranga
 * Ano 2016 - Janeiro a Junho 
 * Aluno Decio Antonio de Carvalho  * 
 */
package visao;


import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static modelo.DBPetFast.criarUsuarioDerby;

/**
 *
 * @author deciodecarvalho
 */
public class TelaUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaUsuario
     */
    public TelaUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUsuario = new javax.swing.JPanel();
        btnUsuarioVoltar = new javax.swing.JButton();
        btnNovoUsuarioBd = new javax.swing.JButton();
        lblLogin = new javax.swing.JLabel();
        tctLogin = new javax.swing.JTextField();
        lblUsuarioSenha = new javax.swing.JLabel();
        tctSenha = new javax.swing.JTextField();

        btnUsuarioVoltar.setBackground(new java.awt.Color(204, 204, 204));
        btnUsuarioVoltar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnUsuarioVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/saidaDireitaRed.png"))); // NOI18N
        btnUsuarioVoltar.setText("Voltar");
        btnUsuarioVoltar.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnUsuarioVoltar.setPreferredSize(new java.awt.Dimension(100, 50));
        btnUsuarioVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioVoltarActionPerformed(evt);
            }
        });

        btnNovoUsuarioBd.setBackground(new java.awt.Color(204, 204, 204));
        btnNovoUsuarioBd.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnNovoUsuarioBd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/bdVerdeAlvo.png"))); // NOI18N
        btnNovoUsuarioBd.setText("Inserir Usuário BD");
        btnNovoUsuarioBd.setIconTextGap(2);
        btnNovoUsuarioBd.setInheritsPopupMenu(true);
        btnNovoUsuarioBd.setMargin(new java.awt.Insets(2, 0, 2, 0));
        btnNovoUsuarioBd.setPreferredSize(new java.awt.Dimension(100, 50));
        btnNovoUsuarioBd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoUsuarioBdActionPerformed(evt);
            }
        });

        lblLogin.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(102, 102, 102));
        lblLogin.setText("Login: ");

        tctLogin.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctLogin.setForeground(new java.awt.Color(51, 51, 51));
        tctLogin.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tctLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tctLoginMouseReleased(evt);
            }
        });

        lblUsuarioSenha.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblUsuarioSenha.setForeground(new java.awt.Color(102, 102, 102));
        lblUsuarioSenha.setText("Senha: ");

        tctSenha.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctSenha.setForeground(new java.awt.Color(51, 51, 51));
        tctSenha.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        javax.swing.GroupLayout panelUsuarioLayout = new javax.swing.GroupLayout(panelUsuario);
        panelUsuario.setLayout(panelUsuarioLayout);
        panelUsuarioLayout.setHorizontalGroup(
            panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuarioLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUsuarioLayout.createSequentialGroup()
                        .addComponent(btnNovoUsuarioBd, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(btnUsuarioVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelUsuarioLayout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addComponent(lblUsuarioSenha)
                            .addGap(18, 18, 18)
                            .addComponent(tctSenha))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelUsuarioLayout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(lblLogin)
                            .addGap(18, 18, 18)
                            .addComponent(tctLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        panelUsuarioLayout.setVerticalGroup(
            panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsuarioLayout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tctLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLogin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tctSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuarioSenha))
                .addGap(71, 71, 71)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUsuarioVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovoUsuarioBd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 101, Short.MAX_VALUE)
                .addComponent(panelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(panelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsuarioVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnUsuarioVoltarActionPerformed

    private void btnNovoUsuarioBdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoUsuarioBdActionPerformed
        //meu codigo aqui
        String login;
        String password;
        String msg;
        login = tctLogin.getText().trim();
        password = tctSenha.getText().trim();
        
        boolean CriarUsuarioDerby = false;
        try {
            CriarUsuarioDerby = criarUsuarioDerby(login, password);
        } catch (ClassNotFoundException ex) {
            
            Logger.getLogger(TelaUsuario.class.getName()).log(Level.SEVERE, null, ex);
            msg ="Ocorreu um erro ao tentar criar novo usuário do Banco de dados \n";
            JOptionPane.showMessageDialog(null, msg+ex );
        }
        if (CriarUsuarioDerby){
            msg ="Usuário: "+login+ " inserido com sucesso";
            JOptionPane.showMessageDialog(null, msg );
        }
    }//GEN-LAST:event_btnNovoUsuarioBdActionPerformed

    private void tctLoginMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tctLoginMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tctLoginMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNovoUsuarioBd;
    private javax.swing.JButton btnUsuarioVoltar;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblUsuarioSenha;
    private javax.swing.JPanel panelUsuario;
    private static javax.swing.JTextField tctLogin;
    private static javax.swing.JTextField tctSenha;
    // End of variables declaration//GEN-END:variables
}
