/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author Décio
 */
public class TelaAnimal extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaAnimal
     */
    public TelaAnimal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPetAnimalTitulo1 = new javax.swing.JPanel();
        lblTituloPet1 = new javax.swing.JLabel();
        lblTelaPetNomePet = new javax.swing.JPanel();
        lblTelaPetNomeCliente = new javax.swing.JLabel();
        tctPetAnimal = new javax.swing.JTextField();
        lblTelaPetNascimento = new javax.swing.JLabel();
        tctPetNascimento = new javax.swing.JTextField();
        tctPetCor = new javax.swing.JTextField();
        lblTelaPetCor = new javax.swing.JLabel();
        lblTelaPetEspecie = new javax.swing.JLabel();
        tctPetEspecie = new javax.swing.JTextField();
        tctPetRaca = new javax.swing.JTextField();
        lblTelaPetRaca = new javax.swing.JLabel();
        lblTelaPetPeso = new javax.swing.JLabel();
        tctPetPeso = new javax.swing.JTextField();
        lblTelaPetAltura = new javax.swing.JLabel();
        tctPetAltura = new javax.swing.JTextField();
        lblTelaPetSexo = new javax.swing.JLabel();
        lblTelaPetCaracteristica = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaPetCaracteristica = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        tctPetFoto = new javax.swing.JTextField();
        lblTelaPetUrlFoto = new javax.swing.JLabel();
        lblTelaPetPesoUnidade = new javax.swing.JLabel();
        lblTelaPetAlturaUnidade = new javax.swing.JLabel();
        rbMacho = new javax.swing.JRadioButton();
        rbFemea = new javax.swing.JRadioButton();
        btnPetSalvar = new javax.swing.JButton();
        btnPetExcluir = new javax.swing.JButton();
        btnPetVoltar = new javax.swing.JButton();

        jPanelPetAnimalTitulo1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblTituloPet1.setBackground(new java.awt.Color(102, 102, 102));
        lblTituloPet1.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        lblTituloPet1.setForeground(new java.awt.Color(102, 102, 102));
        lblTituloPet1.setText("Pet-Animal");

        javax.swing.GroupLayout jPanelPetAnimalTitulo1Layout = new javax.swing.GroupLayout(jPanelPetAnimalTitulo1);
        jPanelPetAnimalTitulo1.setLayout(jPanelPetAnimalTitulo1Layout);
        jPanelPetAnimalTitulo1Layout.setHorizontalGroup(
            jPanelPetAnimalTitulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPetAnimalTitulo1Layout.createSequentialGroup()
                .addContainerGap(517, Short.MAX_VALUE)
                .addComponent(lblTituloPet1)
                .addGap(408, 408, 408))
        );
        jPanelPetAnimalTitulo1Layout.setVerticalGroup(
            jPanelPetAnimalTitulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPetAnimalTitulo1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(lblTituloPet1)
                .addContainerGap())
        );

        lblTelaPetNomePet.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblTelaPetNomeCliente.setBackground(new java.awt.Color(102, 102, 102));
        lblTelaPetNomeCliente.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblTelaPetNomeCliente.setForeground(new java.awt.Color(102, 102, 102));
        lblTelaPetNomeCliente.setText("Nome Pet:");

        tctPetAnimal.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctPetAnimal.setForeground(new java.awt.Color(51, 51, 51));
        tctPetAnimal.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblTelaPetNascimento.setBackground(new java.awt.Color(102, 102, 102));
        lblTelaPetNascimento.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblTelaPetNascimento.setForeground(new java.awt.Color(102, 102, 102));
        lblTelaPetNascimento.setText("Nascimento:");

        tctPetNascimento.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctPetNascimento.setForeground(new java.awt.Color(51, 51, 51));
        tctPetNascimento.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        tctPetCor.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctPetCor.setForeground(new java.awt.Color(51, 51, 51));
        tctPetCor.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblTelaPetCor.setBackground(new java.awt.Color(102, 102, 102));
        lblTelaPetCor.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblTelaPetCor.setForeground(new java.awt.Color(102, 102, 102));
        lblTelaPetCor.setText("Cor:");

        lblTelaPetEspecie.setBackground(new java.awt.Color(102, 102, 102));
        lblTelaPetEspecie.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblTelaPetEspecie.setForeground(new java.awt.Color(102, 102, 102));
        lblTelaPetEspecie.setText("Espécie:");

        tctPetEspecie.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctPetEspecie.setForeground(new java.awt.Color(51, 51, 51));
        tctPetEspecie.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        tctPetRaca.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctPetRaca.setForeground(new java.awt.Color(51, 51, 51));
        tctPetRaca.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblTelaPetRaca.setBackground(new java.awt.Color(102, 102, 102));
        lblTelaPetRaca.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblTelaPetRaca.setForeground(new java.awt.Color(102, 102, 102));
        lblTelaPetRaca.setText("Raça:");

        lblTelaPetPeso.setBackground(new java.awt.Color(102, 102, 102));
        lblTelaPetPeso.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblTelaPetPeso.setForeground(new java.awt.Color(102, 102, 102));
        lblTelaPetPeso.setText("Peso:");

        tctPetPeso.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctPetPeso.setForeground(new java.awt.Color(51, 51, 51));
        tctPetPeso.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblTelaPetAltura.setBackground(new java.awt.Color(102, 102, 102));
        lblTelaPetAltura.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblTelaPetAltura.setForeground(new java.awt.Color(102, 102, 102));
        lblTelaPetAltura.setText("Altura:");

        tctPetAltura.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctPetAltura.setForeground(new java.awt.Color(51, 51, 51));
        tctPetAltura.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblTelaPetSexo.setBackground(new java.awt.Color(102, 102, 102));
        lblTelaPetSexo.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblTelaPetSexo.setForeground(new java.awt.Color(102, 102, 102));
        lblTelaPetSexo.setText("Sexo:");

        lblTelaPetCaracteristica.setBackground(new java.awt.Color(102, 102, 102));
        lblTelaPetCaracteristica.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblTelaPetCaracteristica.setForeground(new java.awt.Color(102, 102, 102));
        lblTelaPetCaracteristica.setText("Características:");

        txaPetCaracteristica.setColumns(20);
        txaPetCaracteristica.setRows(5);
        jScrollPane1.setViewportView(txaPetCaracteristica);

        jLabel1.setText(" ");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tctPetFoto.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        tctPetFoto.setForeground(new java.awt.Color(51, 51, 51));
        tctPetFoto.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblTelaPetUrlFoto.setBackground(new java.awt.Color(102, 102, 102));
        lblTelaPetUrlFoto.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblTelaPetUrlFoto.setForeground(new java.awt.Color(102, 102, 102));
        lblTelaPetUrlFoto.setText("Url:");

        lblTelaPetPesoUnidade.setBackground(new java.awt.Color(102, 102, 102));
        lblTelaPetPesoUnidade.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblTelaPetPesoUnidade.setForeground(new java.awt.Color(102, 102, 102));
        lblTelaPetPesoUnidade.setText("kg.");

        lblTelaPetAlturaUnidade.setBackground(new java.awt.Color(102, 102, 102));
        lblTelaPetAlturaUnidade.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblTelaPetAlturaUnidade.setForeground(new java.awt.Color(102, 102, 102));
        lblTelaPetAlturaUnidade.setText("cm");

        rbMacho.setFont(new java.awt.Font("Times New Roman", 3, 11)); // NOI18N
        rbMacho.setForeground(new java.awt.Color(102, 102, 102));
        rbMacho.setText("Macho");

        rbFemea.setForeground(new java.awt.Color(102, 102, 102));
        rbFemea.setText("Fêmea");

        btnPetSalvar.setBackground(new java.awt.Color(255, 255, 255));
        btnPetSalvar.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnPetSalvar.setForeground(new java.awt.Color(0, 102, 0));
        btnPetSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/inserir.png"))); // NOI18N
        btnPetSalvar.setText("Salvar");
        btnPetSalvar.setMargin(new java.awt.Insets(1, 1, 1, 1));

        btnPetExcluir.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnPetExcluir.setForeground(new java.awt.Color(102, 0, 0));
        btnPetExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/remover.png"))); // NOI18N
        btnPetExcluir.setText("Excluir");
        btnPetExcluir.setMargin(new java.awt.Insets(1, 1, 1, 1));

        btnPetVoltar.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnPetVoltar.setForeground(new java.awt.Color(0, 0, 102));
        btnPetVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/voltarAzul.png"))); // NOI18N
        btnPetVoltar.setText("Voltar");
        btnPetVoltar.setMargin(new java.awt.Insets(1, 1, 1, 1));

        javax.swing.GroupLayout lblTelaPetNomePetLayout = new javax.swing.GroupLayout(lblTelaPetNomePet);
        lblTelaPetNomePet.setLayout(lblTelaPetNomePetLayout);
        lblTelaPetNomePetLayout.setHorizontalGroup(
            lblTelaPetNomePetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblTelaPetNomePetLayout.createSequentialGroup()
                .addGroup(lblTelaPetNomePetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblTelaPetNomePetLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblTelaPetNomeCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tctPetAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(lblTelaPetNomePetLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(lblTelaPetNomePetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, lblTelaPetNomePetLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(lblTelaPetEspecie)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tctPetEspecie))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, lblTelaPetNomePetLayout.createSequentialGroup()
                                .addGroup(lblTelaPetNomePetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTelaPetNascimento)
                                    .addComponent(lblTelaPetRaca)
                                    .addComponent(lblTelaPetCor)
                                    .addComponent(lblTelaPetPeso)
                                    .addComponent(lblTelaPetCaracteristica))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(lblTelaPetNomePetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(lblTelaPetNomePetLayout.createSequentialGroup()
                                        .addComponent(tctPetPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblTelaPetPesoUnidade)
                                        .addGap(58, 58, 58)
                                        .addComponent(lblTelaPetAltura)
                                        .addGap(18, 18, 18)
                                        .addComponent(tctPetAltura))
                                    .addComponent(tctPetCor)
                                    .addComponent(tctPetRaca)
                                    .addGroup(lblTelaPetNomePetLayout.createSequentialGroup()
                                        .addComponent(tctPetNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(lblTelaPetSexo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbMacho)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbFemea))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGroup(lblTelaPetNomePetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblTelaPetNomePetLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lblTelaPetAlturaUnidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(lblTelaPetNomePetLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblTelaPetUrlFoto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(lblTelaPetNomePetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tctPetFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                            .addGroup(lblTelaPetNomePetLayout.createSequentialGroup()
                                .addComponent(btnPetSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(108, 108, 108)
                                .addComponent(btnPetExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPetVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        lblTelaPetNomePetLayout.setVerticalGroup(
            lblTelaPetNomePetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblTelaPetNomePetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lblTelaPetNomePetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(lblTelaPetNomePetLayout.createSequentialGroup()
                        .addGroup(lblTelaPetNomePetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTelaPetNomeCliente)
                            .addComponent(tctPetAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(lblTelaPetNomePetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tctPetEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelaPetEspecie))
                        .addGroup(lblTelaPetNomePetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lblTelaPetNomePetLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(lblTelaPetNomePetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tctPetNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTelaPetNascimento)))
                            .addGroup(lblTelaPetNomePetLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(lblTelaPetNomePetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTelaPetSexo)
                                    .addComponent(rbMacho)
                                    .addComponent(rbFemea))))
                        .addGap(16, 16, 16)
                        .addGroup(lblTelaPetNomePetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tctPetRaca, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelaPetRaca))
                        .addGap(18, 18, 18)
                        .addGroup(lblTelaPetNomePetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tctPetCor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelaPetCor))
                        .addGap(18, 18, 18)
                        .addGroup(lblTelaPetNomePetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tctPetPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelaPetPeso)
                            .addComponent(lblTelaPetAltura)
                            .addComponent(tctPetAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelaPetPesoUnidade)
                            .addComponent(lblTelaPetAlturaUnidade))
                        .addGap(66, 66, 66)
                        .addGroup(lblTelaPetNomePetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblTelaPetNomePetLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(lblTelaPetNomePetLayout.createSequentialGroup()
                                .addComponent(lblTelaPetCaracteristica)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(45, 45, 45))
                    .addGroup(lblTelaPetNomePetLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(lblTelaPetNomePetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTelaPetUrlFoto)
                            .addComponent(tctPetFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(lblTelaPetNomePetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPetSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPetExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPetVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelPetAnimalTitulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTelaPetNomePet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPetAnimalTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTelaPetNomePet, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPetExcluir;
    private javax.swing.JButton btnPetSalvar;
    private javax.swing.JButton btnPetVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelPetAnimalTitulo1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTelaPetAltura;
    private javax.swing.JLabel lblTelaPetAlturaUnidade;
    private javax.swing.JLabel lblTelaPetCaracteristica;
    private javax.swing.JLabel lblTelaPetCor;
    private javax.swing.JLabel lblTelaPetEspecie;
    private javax.swing.JLabel lblTelaPetNascimento;
    private javax.swing.JLabel lblTelaPetNomeCliente;
    private javax.swing.JPanel lblTelaPetNomePet;
    private javax.swing.JLabel lblTelaPetPeso;
    private javax.swing.JLabel lblTelaPetPesoUnidade;
    private javax.swing.JLabel lblTelaPetRaca;
    private javax.swing.JLabel lblTelaPetSexo;
    private javax.swing.JLabel lblTelaPetUrlFoto;
    private javax.swing.JLabel lblTituloPet1;
    private javax.swing.JRadioButton rbFemea;
    private javax.swing.JRadioButton rbMacho;
    private static javax.swing.JTextField tctPetAltura;
    private static javax.swing.JTextField tctPetAnimal;
    private static javax.swing.JTextField tctPetCor;
    private static javax.swing.JTextField tctPetEspecie;
    private static javax.swing.JTextField tctPetFoto;
    private static javax.swing.JTextField tctPetNascimento;
    private static javax.swing.JTextField tctPetPeso;
    private static javax.swing.JTextField tctPetRaca;
    private javax.swing.JTextArea txaPetCaracteristica;
    // End of variables declaration//GEN-END:variables
}
