/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author deciodecarvalho
 */
public class TelaAgendaServico extends javax.swing.JFrame {

    /**
     * Creates new form TelaAgendaServico
     */
    public TelaAgendaServico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAgendaTitulo = new javax.swing.JPanel();
        lblTituloAgendaPet = new javax.swing.JLabel();
        pnlAgenda = new javax.swing.JPanel();
        pnlAbasAgenda = new javax.swing.JTabbedPane();
        jpnlMesAtual = new javax.swing.JPanel();
        lblClienteAgenda = new javax.swing.JLabel();
        lbltCliente = new javax.swing.JLabel();
        lblPetClienteAgenda = new javax.swing.JLabel();
        lbltPetCliente = new javax.swing.JLabel();
        lbltServiço = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        lblfotoPetAgenda = new javax.swing.JLabel();
        lbltIdPetClienteAgenda = new javax.swing.JLabel();
        lblIdClienteAgenda = new javax.swing.JLabel();
        lbltidPet = new javax.swing.JLabel();
        lblIdPetAgenda = new javax.swing.JLabel();
        jpnMesProximo = new javax.swing.JPanel();
        pnlAgendaBotoes = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlAgendaTitulo.setBackground(new java.awt.Color(229, 255, 255));
        pnlAgendaTitulo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        pnlAgendaTitulo.setInheritsPopupMenu(true);

        lblTituloAgendaPet.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        lblTituloAgendaPet.setForeground(new java.awt.Color(102, 102, 102));
        lblTituloAgendaPet.setText("Agenda de Serviços Petfast");

        javax.swing.GroupLayout pnlAgendaTituloLayout = new javax.swing.GroupLayout(pnlAgendaTitulo);
        pnlAgendaTitulo.setLayout(pnlAgendaTituloLayout);
        pnlAgendaTituloLayout.setHorizontalGroup(
            pnlAgendaTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgendaTituloLayout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(lblTituloAgendaPet)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAgendaTituloLayout.setVerticalGroup(
            pnlAgendaTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgendaTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloAgendaPet)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlAgenda.setBackground(new java.awt.Color(204, 229, 229));
        pnlAgenda.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        pnlAgenda.setInheritsPopupMenu(true);

        pnlAbasAgenda.setBackground(new java.awt.Color(229, 255, 255));
        pnlAbasAgenda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jpnlMesAtual.setBackground(new java.awt.Color(255, 255, 255));

        lblClienteAgenda.setBackground(new java.awt.Color(204, 204, 204));
        lblClienteAgenda.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        lblClienteAgenda.setForeground(new java.awt.Color(102, 102, 102));
        lblClienteAgenda.setText(" ");
        lblClienteAgenda.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));

        lbltCliente.setBackground(new java.awt.Color(204, 204, 204));
        lbltCliente.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbltCliente.setForeground(new java.awt.Color(102, 102, 102));
        lbltCliente.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbltCliente.setText("Cliente:");

        lblPetClienteAgenda.setBackground(new java.awt.Color(204, 204, 204));
        lblPetClienteAgenda.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        lblPetClienteAgenda.setForeground(new java.awt.Color(102, 102, 102));
        lblPetClienteAgenda.setText(" ");
        lblPetClienteAgenda.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));

        lbltPetCliente.setBackground(new java.awt.Color(204, 204, 204));
        lbltPetCliente.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbltPetCliente.setForeground(new java.awt.Color(102, 102, 102));
        lbltPetCliente.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbltPetCliente.setText("Animal Pet:");

        lbltServiço.setBackground(new java.awt.Color(204, 204, 204));
        lbltServiço.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbltServiço.setForeground(new java.awt.Color(102, 102, 102));
        lbltServiço.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbltServiço.setText("Serviço Agendado:");

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(102, 102, 102));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Banho", "Tosagem", "Higienização", " " }));
        jComboBox1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));

        lblfotoPetAgenda.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));

        lbltIdPetClienteAgenda.setBackground(new java.awt.Color(204, 204, 204));
        lbltIdPetClienteAgenda.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbltIdPetClienteAgenda.setForeground(new java.awt.Color(102, 102, 102));
        lbltIdPetClienteAgenda.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbltIdPetClienteAgenda.setText("Cliente:");

        lblIdClienteAgenda.setBackground(new java.awt.Color(204, 204, 204));
        lblIdClienteAgenda.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        lblIdClienteAgenda.setForeground(new java.awt.Color(102, 102, 102));
        lblIdClienteAgenda.setText(" ");
        lblIdClienteAgenda.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));

        lbltidPet.setBackground(new java.awt.Color(204, 204, 204));
        lbltidPet.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbltidPet.setForeground(new java.awt.Color(102, 102, 102));
        lbltidPet.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbltidPet.setText("id Pet");

        lblIdPetAgenda.setBackground(new java.awt.Color(204, 204, 204));
        lblIdPetAgenda.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        lblIdPetAgenda.setForeground(new java.awt.Color(102, 102, 102));
        lblIdPetAgenda.setText(" ");
        lblIdPetAgenda.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));

        javax.swing.GroupLayout jpnlMesAtualLayout = new javax.swing.GroupLayout(jpnlMesAtual);
        jpnlMesAtual.setLayout(jpnlMesAtualLayout);
        jpnlMesAtualLayout.setHorizontalGroup(
            jpnlMesAtualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlMesAtualLayout.createSequentialGroup()
                .addGroup(jpnlMesAtualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpnlMesAtualLayout.createSequentialGroup()
                        .addComponent(lbltidPet, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIdPetAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnlMesAtualLayout.createSequentialGroup()
                        .addComponent(lbltServiço, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnlMesAtualLayout.createSequentialGroup()
                        .addComponent(lbltIdPetClienteAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIdClienteAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnlMesAtualLayout.createSequentialGroup()
                        .addComponent(lbltPetCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPetClienteAgenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpnlMesAtualLayout.createSequentialGroup()
                        .addComponent(lbltCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblClienteAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblfotoPetAgenda, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnlMesAtualLayout.setVerticalGroup(
            jpnlMesAtualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlMesAtualLayout.createSequentialGroup()
                .addGroup(jpnlMesAtualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblfotoPetAgenda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpnlMesAtualLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpnlMesAtualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIdClienteAgenda)
                            .addComponent(lbltIdPetClienteAgenda))
                        .addGap(18, 18, 18)
                        .addGroup(jpnlMesAtualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblClienteAgenda)
                            .addComponent(lbltCliente))
                        .addGap(18, 18, 18)
                        .addGroup(jpnlMesAtualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIdPetAgenda)
                            .addComponent(lbltidPet))
                        .addGap(18, 18, 18)
                        .addGroup(jpnlMesAtualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPetClienteAgenda)
                            .addComponent(lbltPetCliente))
                        .addGap(25, 25, 25)
                        .addGroup(jpnlMesAtualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbltServiço, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(477, Short.MAX_VALUE))
        );

        pnlAbasAgenda.addTab("Mês Atual", jpnlMesAtual);

        jpnMesProximo.setBackground(new java.awt.Color(229, 255, 255));

        javax.swing.GroupLayout jpnMesProximoLayout = new javax.swing.GroupLayout(jpnMesProximo);
        jpnMesProximo.setLayout(jpnMesProximoLayout);
        jpnMesProximoLayout.setHorizontalGroup(
            jpnMesProximoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 837, Short.MAX_VALUE)
        );
        jpnMesProximoLayout.setVerticalGroup(
            jpnMesProximoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 701, Short.MAX_VALUE)
        );

        pnlAbasAgenda.addTab("Mês Próximo", jpnMesProximo);

        javax.swing.GroupLayout pnlAgendaLayout = new javax.swing.GroupLayout(pnlAgenda);
        pnlAgenda.setLayout(pnlAgendaLayout);
        pnlAgendaLayout.setHorizontalGroup(
            pnlAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAgendaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAbasAgenda)
                .addContainerGap())
        );
        pnlAgendaLayout.setVerticalGroup(
            pnlAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAgendaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAbasAgenda)
                .addContainerGap())
        );

        pnlAgendaBotoes.setBackground(new java.awt.Color(178, 204, 204));
        pnlAgendaBotoes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        pnlAgendaBotoes.setInheritsPopupMenu(true);

        javax.swing.GroupLayout pnlAgendaBotoesLayout = new javax.swing.GroupLayout(pnlAgendaBotoes);
        pnlAgendaBotoes.setLayout(pnlAgendaBotoesLayout);
        pnlAgendaBotoesLayout.setHorizontalGroup(
            pnlAgendaBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlAgendaBotoesLayout.setVerticalGroup(
            pnlAgendaBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAgendaTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlAgenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlAgendaBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlAgendaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAgendaBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAgendaServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAgendaServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAgendaServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAgendaServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAgendaServico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JPanel jpnMesProximo;
    private javax.swing.JPanel jpnlMesAtual;
    private javax.swing.JLabel lblClienteAgenda;
    private javax.swing.JLabel lblIdClienteAgenda;
    private javax.swing.JLabel lblIdPetAgenda;
    private javax.swing.JLabel lblPetClienteAgenda;
    private javax.swing.JLabel lblTituloAgendaPet;
    private javax.swing.JLabel lblfotoPetAgenda;
    private javax.swing.JLabel lbltCliente;
    private javax.swing.JLabel lbltIdPetClienteAgenda;
    private javax.swing.JLabel lbltPetCliente;
    private javax.swing.JLabel lbltServiço;
    private javax.swing.JLabel lbltidPet;
    private javax.swing.JTabbedPane pnlAbasAgenda;
    private javax.swing.JPanel pnlAgenda;
    private javax.swing.JPanel pnlAgendaBotoes;
    private javax.swing.JPanel pnlAgendaTitulo;
    // End of variables declaration//GEN-END:variables
}
